use_frameworks!

platform :ios, '9.0'

target 'SYAlamofire_Example' do
  pod 'SYAlamofire', :path => '../'

  target 'SYAlamofire_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
